-- AlterTable
ALTER TABLE "User" ADD COLUMN     "agility" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "critRate" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN     "equipBoots" TEXT,
ADD COLUMN     "equipChest" TEXT,
ADD COLUMN     "equipGloves" TEXT,
ADD COLUMN     "equipHelmet" TEXT,
ADD COLUMN     "equipLegs" TEXT DEFAULT 'BasicPants',
ADD COLUMN     "equipRing" TEXT,
ADD COLUMN     "equipShield" TEXT,
ADD COLUMN     "equipShoulders" TEXT DEFAULT 'BasicShoulder',
ADD COLUMN     "equipTrinket" TEXT,
ADD COLUMN     "equipWeapon" TEXT DEFAULT 'FireWeaponItem',
ADD COLUMN     "exp" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "gold" INTEGER NOT NULL DEFAULT 10001,
ADD COLUMN     "hp" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "intelligence" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "inventory" TEXT[] DEFAULT ARRAY['BasicSword', 'DragonBootsItem', 'IronGlovesItem', 'BasicGreenShoulderItem', 'ShredShieldItem', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']::TEXT[],
ADD COLUMN     "level" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "mana" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "maxHp" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "maxMana" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "strength" INTEGER NOT NULL DEFAULT 10;
