/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 basicShoulders.glb 
*/

import React, { useEffect, useMemo, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from 'three';

type Props = {
  skeleton?: THREE.Skeleton
  url?: string
}
export default function BasicShoulders({
  skeleton,
  url = "/items/shoulders/basicShoulders.glb",
  ...props
}: Props) {
  const group = useRef<THREE.Group>(null!)
  const { nodes, materials, } = useGLTF(url) as unknown as {
    nodes: Record<string, any>;
    materials: Record<string, THREE.Material>;

  };
  const mesh1 = useRef<THREE.SkinnedMesh>(null);
  const mesh2 = useRef<THREE.SkinnedMesh>(null);
  useEffect(() => {
    if (!skeleton) return;
    mesh1.current?.bind(skeleton, mesh1.current.bindMatrix);
    mesh2.current?.bind(skeleton, mesh2.current.bindMatrix);
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Rig">
          <primitive object={nodes.root} />
          <skinnedMesh
            frustumCulled={false}
            // material-side={THREE.DoubleSide}
            ref={mesh1}
            name="Object_18" geometry={nodes.Object_18.geometry} 
            // material={materials.rshoulder_plate_alliance_211c997}
             skeleton={nodes.Object_18.skeleton}>
            <meshStandardMaterial color="red" />
             </skinnedMesh>
          <skinnedMesh
            ref={mesh2}
            name="Object_19" geometry={nodes.Object_19.geometry} material={materials.lshoulder_plate_alliance_09f994c} skeleton={nodes.Object_19.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/basicShoulders.glb')
