/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 basicShoulders.glb 
*/

import React, { useEffect, useMemo, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from 'three';

type Props = {
  skeleton?: THREE.Skeleton
  url?: string
}
export default function BasicGreenShoulder({
  skeleton,
  url = "/items/shoulders/basicShoulders.glb",
  ...props
}: Props) {
  const group = useRef<THREE.Group>(null!)
  const { nodes, materials, } = useGLTF(url) as unknown as {
    nodes: Record<string, any>;
    materials: Record<string, THREE.Material>;

  };
  const mesh1 = useRef<THREE.SkinnedMesh>(null);
  const mesh2 = useRef<THREE.SkinnedMesh>(null);
  const mesh3 = useRef<THREE.SkinnedMesh>(null);
  const mesh4 = useRef<THREE.SkinnedMesh>(null);
  useEffect(() => {
    if (!skeleton) return;
    mesh1.current?.bind(skeleton, mesh1.current.bindMatrix);
    mesh2.current?.bind(skeleton, mesh2.current.bindMatrix);
    mesh3.current?.bind(skeleton, mesh3.current.bindMatrix);
    mesh4.current?.bind(skeleton, mesh4.current.bindMatrix);

  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Rig">
          {/* <primitive object={nodes.root} /> */}
          <group name="Object_18" >
            <skinnedMesh
              frustumCulled={false}
              ref={mesh1}
              name="Object_11"
              geometry={nodes.Object_11.geometry}
              material={materials.Material}
              skeleton={nodes.Object_11.skeleton}
            >
                {/* <meshStandardMaterial color="green" /> */}
            </skinnedMesh>
            <skinnedMesh
              frustumCulled={false}
            ref={mesh2}
              name="Object_11_1"
              geometry={nodes.Object_11_1.geometry}
              material={materials['Material.001']}
              skeleton={nodes.Object_11_1.skeleton}
            >
                <meshStandardMaterial color="green" />
            </skinnedMesh>
          </group>
          <group name="Object_19001" >
            <skinnedMesh
              frustumCulled={false}
              ref={mesh3}
              name="Object_12003"
              geometry={nodes.Object_12003.geometry}
              material={materials.Material}
              skeleton={nodes.Object_12003.skeleton}
            />
            <skinnedMesh
              frustumCulled={false}
              ref={mesh4}
              name="Object_12003_1"
              geometry={nodes.Object_12003_1.geometry}
            //   material={materials['Material.001']}
              skeleton={nodes.Object_12003_1.skeleton}
            >
                <meshStandardMaterial color="green" />
            </skinnedMesh>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/items/shoulders/basicShoulders.glb')
