[build]
  base = "client" 
  command = "yarn && yarn run build"
  publish = "dist"

# Si tienes un server con handler
[functions]
  directory = "server"

[[redirects]]
from = "/*"
to = "index.html"
status = 200