/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useLayoutEffect, useMemo, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

type TreeMainPlaceProps = {
  count?: number
  range?: number
}

export function TreeMainPlace({ count = 3, range = 50, ...props }: TreeMainPlaceProps) {
  const { nodes, materials } = useGLTF('/environment/tree.glb')
  const branchesRef = useRef<THREE.InstancedMesh>(null)
  const leavesRef = useRef<THREE.InstancedMesh>(null)
  const tempObject = useMemo(() => new THREE.Object3D(), [])

  const instances = useMemo(() => {
    return Array.from({ length: count }, () => ({
      x: (Math.random() * 2 - 1) * range,
      z: (Math.random() * 2 - 1) * range,
      y: 0,
      ry: Math.random() * Math.PI * 2,
      s: 0.85 + Math.random() * 0.4,
    }))
  }, [count, range])

  useLayoutEffect(() => {
    if (!branchesRef.current || !leavesRef.current) return

    instances.forEach((item, index) => {
      tempObject.position.set(item.x, item.y, item.z)
      tempObject.rotation.set(0, item.ry, 0)
      tempObject.scale.set(item.s, item.s, item.s)
      tempObject.updateMatrix()
      branchesRef.current!.setMatrixAt(index, tempObject.matrix)
      leavesRef.current!.setMatrixAt(index, tempObject.matrix)
    })

    branchesRef.current.instanceMatrix.needsUpdate = true
    leavesRef.current.instanceMatrix.needsUpdate = true
  }, [instances, tempObject])

  return (
    <group {...props} dispose={null} scale={0.2}>
      <instancedMesh
        ref={branchesRef}
        args={[(nodes.mesh_0 as THREE.Mesh).geometry, materials.branches, count]}
        castShadow
        receiveShadow
      />
      <instancedMesh
        ref={leavesRef}
        args={[(nodes.mesh_1 as THREE.Mesh).geometry, materials.leaves, count]}
        castShadow
        receiveShadow
      />
    </group>
  )
}

useGLTF.preload('/tree.glb')